[project]
site_name = "AD's Coding Diary"
site_description = "This is my coding diary."
site_author = "Abhisek Das"
site_url = "https://adas-cpbook.pages.dev/"
copyright = "Copyright &copy; 2025 Abhisek Das"

nav = [
    {"Home" = "index.md"},
    {"C++" = [
        "cpp/index.md",
        "cpp/vector.md"
    ]},
    {"Graph" = [
        "graph/bfs.md",
        "graph/dfs.md",
        "graph/toposort.md",
        "graph/dijkstra.md"
    ]},
    {"Trie" = [
        "trie/trie.md",
        "trie/count-distinct-substrings.md"
    ]}
]

extra_javascript = [
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]

extra_css = [
    "https://unpkg.com/katex@0/dist/katex.min.css"
]

[project.theme]
variant = "modern"
language = "en"
logo = "images/favicon.png"
favicon = "images/favicon.png"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.tabs",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]
font.text = "Inter"
font.code = "JetBrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
